server:
  port: 4000

spring:
  application:
    name: spring-boot-cli
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_demo_cli?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "!Ab123456"
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: relive-client
          client-secret: relive-client

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/pt/db/*.xml

logging:
  level:
    cn.library.mapper: debug