server:
  port: 4000

spring:
  application:
    name: spring-boot-cli
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_demo_cli?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 13633383232

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/pt/db/*.xml

logging:
  level:
    cn.library.mapper: debug
